### ISSUE TITLE
Problems with advanced romms 

### ISSUE THREAD

**Issue by HennieLP** [ESPresense/ESPresense-companion#12]
how it is 
![grafik](https://user-images.githubusercontent.com/65833107/205461782-bbac84bc-1568-4e18-9a84-842facfdb842.png)

how it schud be 

![grafik](https://user-images.githubusercontent.com/65833107/205462217-bf79732f-50dc-4380-84f7-3c8f11afb6c9.png)

config
```
      - name: Schlafen
        points:
          - [8.35, 9.80]
          - [8.4, 13.75]
          - [12.3, 13.75] #the point that is missing
          - [12.3, 10.25]
          - [14.1, 10.25]
          - [14.1, 7.7] 
```

![grafik](https://user-images.githubusercontent.com/65833107/205461959-750aed23-d52f-4094-a348-c2819a7fac5b.png)

**Comment by DTTerastar** [comment]
Yes, I do something that could cause that.  I'll look into it.

**Comment by DTTerastar** [comment]
Oh, I think you are missing a point.  I count you should have 7 points since the start and end should match.

**Comment by HennieLP** [comment]
like this ?

```
          - [8.35, 9.80]
          - [8.4, 13.75]
          - [12.3, 13.75]
          - [12.3, 10.25]
          - [14.1, 10.25]
          - [14.1, 7.7]
          - [8.35, 9.80]

```

**Comment by DTTerastar** [comment]
Yeah I use this [https://observablehq.com/@d3/d3-polygonhull], that's the issue.  We don't want a convex hull

**Comment by DTTerastar** [comment]
v0.1.10 should fix this.  Please verify.

**Comment by HennieLP** [comment]
![grafik](https://user-images.githubusercontent.com/65833107/205463088-cbd3e02a-287b-43f0-a773-1ae0cd042e50.png)

works now thx !

**Comment by DTTerastar** [comment]
Awesome
