### ISSUE TITLE
Config option to lock aspect ratio

### ISSUE THREAD

**Issue by theYoYo** [ESPresense/ESPresense-companion#126]
I've struggled to find an easy way to change the Y value display reference scaling (currently has a scaling reference that looks to be aligned to the bounding area. This causes the display to skew the representation. 

I thought as an enhancement to the project could be some way to modify the view in terms of scaling to bounding area, scaling 100%, zoom/zoom out for possibly some larger implementations.

I scrunch up the display window for now when I want things to look normal

<img width="748" alt="Screenshot 2023-04-03 at 9 41 18 AM" src="https://user-images.githubusercontent.com/8586768/229543669-7a609d73-d66a-4fb1-b439-013edf4e2a37.png">

**Comment by fsedarkalex** [comment]
I'd love to see the option to disable the per-axis scaling so I can set the display so that X and Y are scaled the same, so that 1*1m is actually displayed square on the screen

**Comment by fsedarkalex** [comment]
.
