### ISSUE TITLE
Allow configuration to include a location for a device and use that as part of calibration

### ISSUE THREAD

**Issue by fsedarkalex** [ESPresense/ESPresense-companion#131]
Hi! Super cool someone finally is creating a trilateration tool for ESPresense!
I got no idea how to code this but I got an idea I wanted to share:

As nodes can see each other it should already be possible to optimize detection based on measurements. I think this is what you're likely working on.

I thought to get one step further:
What about placing an iBeacon or Eddystone at a specific location and enter the actual distances to the nodes - or better: placing it visually on the floormap.
The system could then calculate the calibration values out of the actual measurements per node.
This could be done multiple times from different locations to improve the measurements and calibration.

**Comment by DTTerastar** [comment]
Yeah, I have a TV that is always in the same spot and it'd be nice to use it to calibrate (along w/ the nodes).  Something like a location: on the devices yaml could do it.  I've had to rewrite all the optimization stuff a bunch of times and yeah this would probably need another pretty big change to the code...

**Comment by fsedarkalex** [comment]
I am thinking not only of a fixed device at a fixed spot but more like a calibration that is done "once" (we all only configure our stuff once, right? :D ) so you could use one beacon to calibrate everything.

**Comment by DTTerastar** [comment]
The calibration has to be somewhat continuous because just walking around our house moves bags of absorption around (we're mostly salt water that absorbs rf really well).  There are in fact some research that can detect a person in a room just by looking at the absorption going up at a certain spot.

**Comment by operator207** [comment]
> ...walking around our house moves bags of absorption around (we're mostly salt water that absorbs rf really well)....

Hearing the above, I can stop laughing and thinking of this. https://www.youtube.com/watch?v=LAlqp0_a0tE

On a serious note, I have a bunch of trackers (trackr pixel) and would be happy to sacrifice a few to get higher resolution. Right now I have dogs that are asleep but merging through walls on a 1 second basis between the back room and the living room. And now she is in the front yard.

**Comment by DTTerastar** [comment]
Yeah, The calibration just needs more math.  I think we already have all the data we need, I just need to learn more linear algebra.  (And yes, I was totally riffing on that Star Trek ep!)

**Comment by bakerkj** [comment]
This is a great idea!

**Comment by scaytrase** [comment]
I'm not sure if it was that actually suggested, but I'd like to see calibration based on desired and measured nodes location (as an error to minimise). We already have all the data needed to the calibration, thus my nodes "float" on the other side of the house, while error is not that big (i.e 1m)

![image](https://github.com/ESPresense/ESPresense-companion/assets/6578413/d7f7142b-a176-4f78-b818-2c98bbaa6324)
![image](https://github.com/ESPresense/ESPresense-companion/assets/6578413/f26a0b99-2345-4bcd-9a5f-7641ebf908ae)

marked nodes are physically located on the other side of the house. as far as I understand current calibration tries to minimise distance error between nodes, but not the location of nodes itself

**Comment by DTTerastar** [comment]
The dot for the node is not part of calibration.  It's just where the algo would put it if it's a device.  It's kinda dumb.  I put it in to try and see how well everything was working, but it's consistently the only thing that the location is totally wrong.  It would obviously be perfect if I used the distance of 0 from the node to the device. But then what's the point?

**Comment by scaytrase** [comment]
> The dot for the node is not part of calibration

Yea, it's not now, but I'm suggesting to somehow use it. Because it's the pure indicator of trilateration precision. If the node point is too far away from the location there node should be - that means other nodes measure wrong distances to it

**Comment by DTTerastar** [comment]
But calibration itself uses the mapped distances and compares them to the measured distance.  It tries various values for absorption and rxAdj and sees how well it fits.

The change to get rid of the circles is in: https://github.com/ESPresense/ESPresense-companion/pull/309

**Comment by jodom1979** [comment]
I'm encountering difficulties with the optimization process. The documentation doesn't provide much detail about the internal workings. My main confusion is about how the optimization process assigns values like absorption and others.

Here's how the optimization is configured:
optimization:
  enabled: true
  interval_secs: 3600
  limits:
    absorption_min: 2.5
    absorption_max: 5
    tx_ref_rssi_min: -70
    tx_ref_rssi_max: -50
    rx_adj_rssi_min: -15
    rx_adj_rssi_max: 20
    
Considering these default settings, I'm unsure if the integration stores these values in the app's memory, or if it's supposed to dynamically adjust the values on the node, which I could then monitor using MQTT explorer or HASS.

If these settings are adjusted on the node, can I see these changes in real-time on MQTT explorer in my rooms as the calibration begins? And should these real-time values reflect in the calibration chart?

I have enabled the 'retain' option. When I restart a node, it seems to remember the last value it was set to. For example, the absorption changes to 3.75 from 3.5 after a reboot with the retain option enabled. However, I don't see it adjusting to a new value after that.

I'm really enthusiastic about this project overall. I just need more understanding of the best way to calibrate it. Adjusting my phone's RSSI@1m seems effective, but any additional advice would be greatly valued.

**Comment by DTTerastar** [comment]
3600 is an hour.  Put it to 60 and you can see it adjusting a bunch.  It doesn't have any real state.  It just compares the last result to the current to see if it's better and then writes it to all the nodes.  It's a WIP, i'm not happy with what it does atm but I think it's better than nothing.

**Comment by jodom1979** [comment]
Thanks for the info, this does help me better understand what's going on. 

I adjusted it down and indeed I can see the absorption values being written to different states via the explorer. Tested by resetting the absorption value and then watching it go back to 3.75 on their own. So far it always goes back to 3.75. Should I also see any of the rssi values being adjusted too? 

Thanks again for the help!

![image](https://github.com/ESPresense/ESPresense-companion/assets/1341041/84053734-1d69-475a-a021-ba425662c8f4)

**Comment by DTTerastar** [comment]
> Should I also see any of the rssi values being adjusted too? 

The rssi rx adjust should also be adjusted if you have hardware that is different from each other.  I have a bunch of S3 and C3 that have better sensitivity than my ESP 32s and They get positive RX adjustments.  The way it works is it just assumes all of the absorptions are in the middle of the band and looks to see if adjusting the RSSIRX would improve the overall accuracy.
