### ISSUE TITLE
How can I improve calibration?

### ISSUE THREAD

**Issue by AlmostInteractive** [ESPresense/ESPresense-companion#155]
![image](https://user-images.githubusercontent.com/3893631/232938684-f86def55-9b9e-404b-ae88-e896236ffb57.png)
(I don't know why `Dining` doesn't show up on the left hand side.)

![image](https://user-images.githubusercontent.com/3893631/232938818-bc87dda4-dc2d-4c23-bf9b-a5cb2e2affc7.png)

How can I improve calibration?  In reality my phone is at the red X with direct line of sight to `livingroom01/02/03` and `dining`, with a single wall between it and `kitchen`.  Here it's a good 7m away from the actual position and is never closer than 3m from the actual position.

**Comment by DTTerastar** [comment]
Those circles are way too big.  Click on your phone and pick a new rssi@1m.
