### ISSUE TITLE
Local coordinates being displayed on the HA world map

### ISSUE THREAD

**Issue by ShonP40** [ESPresense/ESPresense-companion#169]
After configuring the companion app, I noticed that all configured devices are now being displayed on the Home Assistant world map with their local in-house coordinates.

Could you configure it in a way that makes HA ignore these device trackers?

![image](https://github.com/ESPresense/ESPresense-companion/assets/13995143/93600616-6829-4566-97f1-b55adf9fb143)
![image](https://github.com/ESPresense/ESPresense-companion/assets/13995143/c857413a-4663-402f-b0d7-b7216b79528c)

**Comment by DTTerastar** [comment]
Lattitude and Longitude are 0 because you didn't set your 0,0,0 point in the configuration.  I do think it's a good idea to exclude those in that case.

**Comment by ShonP40** [comment]
oh, I downloaded the companion a while ago so I had the old config, it didn't have the GPS section

**Comment by ShonP40** [comment]
its fine now that I configured it so I guess that this can be closed

**Comment by DTTerastar** [comment]
I fixed it anyways :)

**Comment by ShonP40** [comment]
yea, noticed
Thanks!
