### ISSUE TITLE
Stand alone or HA core

### ISSUE THREAD

**Issue by rhamblen** [ESPresense/ESPresense-companion#226]
Hi
I have home assistant core running on unraid in a docker.
As such I cant use ESPresense companion.  
Is there anyway it can be an integration rather than an addon, so we can load it from HACS?

Or can it be a stand along app?

**Comment by DTTerastar** [comment]
The docker container runs just fine independently of hass.  Have you tried:

```docker run espresense/espresense-companion```

**Comment by rhamblen** [comment]
Doh... I just read the instructions to install in HA, and didnt really look at the files!
I'll just install the docker and try that.

**Comment by DTTerastar** [comment]
Please submit any doc updates that would help future users!

**Comment by rhamblen** [comment]
For reference for those using unraid.

Unraid _> Docker-> add container
make sure your network type is Host (or you wont connect to the mqtt server)
Add the path so you can then edit the config.yaml 
Finally dont forget you are on port 8267, for completeness you might want to add this as a port. 
This means it should now work for people.

![image](https://github.com/ESPresense/ESPresense-companion/assets/16073422/cc7d5212-e9a8-42d1-8d23-85ace27276fe)
