### ISSUE TITLE
Companion showing reused names for different devices

### ISSUE THREAD

**Issue by joshuaboniface** [ESPresense/ESPresense-companion#248]
This started suddenly in the last few versions (after [v0.3.27](https://github.com/ESPresense/ESPresense-companion/releases/tag/v0.3.27)) but I'm not 100% sure which one from my cursory look over the changelogs.

I've got two explicitly configured `iBeacon` devices like so:

```
253 # Devices to track
254 devices:
255   - id: "iBeacon:fdbb94fc-5d04-4dd1-a85c-85430d91812b-100-1"                                                                                                                                                                               
256     name: "Joshua's Phone"
257   - id: "iBeacon:33e6536e-1e48-46dc-9c4e-ace9b9e04ee6-100-1"
258     name: "Michael's Phone"
```

However, the companion is generating several other "devices" with the same name, but with different ID formats and which show different locations:

![image](https://github.com/ESPresense/ESPresense-companion/assets/4031396/4532ee1d-7535-49d6-a2d6-dbdad858bc1c)

Not sure if this is a bug or a side-effect of a recent config change (e.g. what prompted https://github.com/ESPresense/ESPresense-companion/commit/838ea11cf5cb3a127ea9d9f84b90fc21b2071bdf) that I've missed, so advice would be appreciated :-)

**Comment by joshuaboniface** [comment]
The devices there are both Android phones (I'm using the BLE transmitter "sensor" from the HA companion app on both phones), so it's possible that is legitimate then. Maybe it was something in HA that changed :thinking:

**Comment by joshuaboniface** [comment]
Even weirder, as I try to exclude these, it seems to be creating even more new ones, now they're `apple:` IDs.

![image](https://github.com/ESPresense/ESPresense-companion/assets/4031396/06ad539a-0c36-44fc-881d-b2e1f4003c87)

**Comment by DTTerastar** [comment]
Has anyone seen this lately?

**Comment by DTTerastar** [comment]
I believe this is fixed
