### ISSUE TITLE
0.3.31 Breaks WebUI

### ISSUE THREAD

**Issue by GVDub** [ESPresense/ESPresense-companion#256]
Updated to 0.3.31 and all sections of the WebUI are badly broken. No icon graphics loading (just the camera icon indicating broken links), text checkboxes, and the map display is just totally wonky, with the rooms in color toward the bottom, black ellipses at the top, and the stats displayed as plain text below the rooms. 

Tried uninstalling and reinstalling, but got the same results. Running HAOS in a ProxMox VM on a Beelink S12 N95 NUC-style box.

**Comment by DTTerastar** [comment]
Yeah, something I upgraded in npm killed it.  I fixed it in 0.3.35.
