### ISSUE TITLE
How to connect to espresense node?

### ISSUE THREAD

**Issue by findthelorax** [ESPresense/ESPresense-companion#312]
I finally got this mostly setup. Ive made my floorplan and labeled my nodes and their location but they all show inactive and no devices, is there another step i'm missing to link to my espresense nodes?

I have setup a MQTT server and can see the espresense devices in home assistant.
I can see my nodes in the node list. They are all green and I have buttons for update and visit for 3 out of the 4 I have setup.
Devices showed my configured phone once but never updated or gave me any data except n/a or 0.

**Comment by maxistviews** [comment]
What was your solution here?

**Comment by findthelorax** [comment]
I believe I re-setup the MQTT server and I got it working, though currently it isn't working again for me. I figured it was my fault somewhere but perhaps there is an issue. I love this idea but never got it actually working.
