### ISSUE TITLE
Feature request: Mark known devices as away (when they’re away) when restarting the addon

### ISSUE THREAD

**Issue by ShonP40** [ESPresense/ESPresense-companion#336]
At the moment, if I restart the integration while a device isn’t in range of my nodes, the integration wont update its MQTT entity to away, nor even keep displaying it on the devices tab.

It’d be nice to have the integration update each MQTT entity to away if it hasn’t been seen by the integration after startup.

Also, I’ve noticed that sometimes some devices become stuck & keep reporting as being in a specific room even when they’re not in Bluetooth range anymore.

**Comment by DTTerastar** [comment]
yes, we need to store a state file and deal w/ stuff better after restart

**Comment by ShonP40** [comment]
Becoming kinda annoying that it keeps showing the location on the map & in HA when the device isn’t even home for a while

![image](https://github.com/ESPresense/ESPresense-companion/assets/13995143/52a45ca2-6383-456a-8fa8-96a75d609c06)

**Comment by DTTerastar** [comment]
I've been thinking about how to fix this and I am getting closer.  Instead of using a config file, i'm going to use the retained messages under discovery to remember that I had set it up.

**Comment by ShonP40** [comment]
This hasn’t been resolved yet.

**Comment by ShonP40** [comment]
Still an issue

**Comment by DTTerastar** [comment]
@ShonP40 Let me know if this works for you!

**Comment by ShonP40** [comment]
I'll test it in a few days once I get back home

Thanks for implementing it tho!
