### ISSUE TITLE
New release v0.4.0 after v3.4.0? 

### ISSUE THREAD

**Issue by CoMPaTech** [ESPresense/ESPresense-companion#360]
Also the release notes button in the adding shows 'initial release' with 0.0.0

Would it help if I'd take some time on writing up a PR accordingly?

**Comment by DTTerastar** [comment]
It's 0.3.4->0.4.0.  I haven't released the add-on because the popup to update firmware is broken because of this issue:

https://github.com/square/svelte-store/issues/86

Upvote to help get it fixed!

**Comment by DTTerastar** [comment]
I tried forking and fixing it myself, then I understood the world of pain, so I got rid of it.  New version is released!

**Comment by CoMPaTech** [comment]
Great work, works on my HA to upgrade
