### ISSUE TITLE
Unstable device location and slow updates

### ISSUE THREAD

**Issue by abishur** [ESPresense/ESPresense-companion#394]
I'm using a Samsung S20+ (Android) phone with Home Assistant providing a beacon so my phone can be tracked.

In the BLE Transmitter settings I've put my advertise mode at 10Hz and my power at Ultra Low (though I've also tried at high with the same results).

I've flashed 4 ESP32s with the ESPresense firmware and placed them in my office, one at either end of a u shaped hallway, and one in the room adjacent to the office.

I've made no changes to the default configs beyond entering my co-ordinates for the map and telling it where my nodes are located.

I've measure my  RSSI@1M using the ESP32 and holding my phone 1M away from it and set it the settings area.

Despite that my device keeps getting lost (I think the beacon just stops reporting since the LastHit is 2 minutes ago and growing), and when it is found it jumps all over the place.  When I walk around it tends to take about 60 seconds before it updates where I am (which even at 1Hz should still update within a second of me walking around)

I feel like I'm missing something obvious here, but I'm not sure what it is 🤦‍♂️

**Comment by DTTerastar** [comment]
I've found the ha screen to edit those sensor settings is buggy, sometimes I need to go in and flip the settings and eventually it "takes".  Use another phone and confirm you're *actually* at 10hz.  Also if your missing pings it might be Ultra low is too low.  I use lowLatency and medium power.  Also make sure you've disabled maxDistance.  If you're rssi@1m is off you might be hitting the 16m max.

**Comment by abishur** [comment]
I'll give the nRF Connect a test, thanks.

On the maxDistance, I haven't put anything in, should I put in 0 or should I put in a hard limit on the filter to about my room size to prevent excessive overlapping when I'm not testing it?

**Comment by abishur** [comment]
Oh and on the rssi@1m, it seems like my actual signal is stupid low at 1m, like -81.  I'm not sure it this is an android thing or a Samsung thing or what, but it's that way on my phone and my samsung tablet as well, I'm trying to see why my bluetooth radio strength is so weak.

**Comment by DTTerastar** [comment]
Ultra Low and -81 tracks.  Try medium.

**Comment by abishur** [comment]
Okay I tried to update to medium, and low Latency (I also tried to use Beacon Scope to see if that would work better than home assistant).  I made sure that they have no restrictions on power usages and can run in the background.  Looking at the devices information on Home Assistant I will see it's x,y,z coordinates and can see it should be in a room, but it will say n/a for the room/floor.  Then it will drop to unavailable for a minute and come back, but I haven't moved my phone and can confirm in the nRF Connect that it is sending out a signal.

I tried to bump it up to High power but I didn't see any change.  And I also went through and redid all my measurements making sure I was as close as I could get for room positions.  I'm fairly confident that my ESP32 are within a half foot of reality.
I have 6 of them spread across my upstairs, one at each corner of the upstairs and one on either end of a hallway.

It's hard to tell, but I noticed when I was listening to the espresense/rooms/# topic I was getting a lot of telemetry messages with an uptime around "3800".  Is this indicating that my devices are resetting frequently?

**Comment by DTTerastar** [comment]
Uptime of 1 hour isn't good.  I am working through crashes in the betas (especially on b0).  Some super cheap esp32s do have some issues w/ uptime (honestly we're pushing the rf circuit so hard even an occasional m5 esp32 has issues).

Put this on your home assistant dashboard

```
type: custom:auto-entities
card:
  type: history-graph
  hours_to_show: 8
filter:
  include:
    - entity_id: sensor.espresense_*_uptime
sort:
  method: friendly_name
```

Share your graph with me if you can.  I just looked and v3.3.2.b1 is actually looking quite good:

![image](https://github.com/ESPresense/ESPresense-companion/assets/1491145/c550c427-46af-4297-835c-7bee5b35fe3a)

**Comment by abishur** [comment]
I actually updated to v3.3.2b1 to try and get it stabilized and my uptime is around 140,000 which tracks for when I ran  the update on Wednesday evening.

But I'm still getting flaky/slow location.  If I drop the timeout or interval settings in the config will that improve how quickly it detects me moving about?

For the flaky location, could it be because I'm having a lot of error in my calibration settings?

![image](https://github.com/ESPresense/ESPresense-companion/assets/1671047/65a7eef1-4610-4850-bc7f-863699d2d7d3)

I've used a laser tape measure to map out my house and made sure to include things like gaps for wall thickness, so I'm pretty confident I have things pretty spot on.  I mean I've got a lot of not straight angles that I had to do some math to figure out distances so I might have a foot of error by the end of it, but 6m of error seems a bit much.

Do I need to bring down all the ESPs and bring things up 1 at a time, dial in the calibration and then bring up the next one?

**Comment by RaoulSargent** [comment]
FWIW:
I know I am using older ESPresense firmware, but I thought I would share these two charts... I think they are confirming that different esp hardware behaves differently, despite all be esp32 D1 Mini, all from the same supplier AZ-Delivery, but purchased at different times.
All are esp32 D1 Mini, all running espresense v3.3.1, all with the same settings (except name).
approx half of them crash/reboot after about 1 hour, whilst the others have been running now for more than 8 days.

<img width="1797" alt="image" src="https://github.com/ESPresense/ESPresense-companion/assets/61843699/3d2b3bd9-2ab8-4934-bc8c-63fcac89fdcb">
<img width="1797" alt="image" src="https://github.com/ESPresense/ESPresense-companion/assets/61843699/4800426f-272b-4018-8f52-887d920aca1a">

**Comment by DTTerastar** [comment]
Yeah, the brandless stuff on amazon stinks.  But it's so much easier to prime to your house.  I feel like we should have some kind of warning on https://github.com/ESPresense/ESPresense.github.io/blob/master/base-stations.md
