### ISSUE TITLE
[Question] What accuracy can be achiev (in meter)?

### ISSUE THREAD

**Issue by ozett** [ESPresense/ESPresense-companion#41]
got interested in locting BT-devices wie ESPRENSE, but to much variation in simple RSSI.

do you have achieved a accuray **better than 1,5m** ( shorter distance means closer to the original location)?

https://github.com/1technophile/OpenMQTTGateway/issues/783#issuecomment-1369608816

**Comment by DTTerastar** [comment]
The rssi is very good when close by so the key is lots of nodes working together. But we aren't super good yet, lots more work and math needed.

**Comment by ozett** [comment]
have espresence running for some time now, and auto-updating itself to the newest level 😄 
i`ll keep on following your progessions on this all, and stay subscribed to all events,

even if i can not really make a practical use of it for my homeautomation at this time..
but new year even started .. 😁
