### ISSUE TITLE
Add logging of initial guess when ExceedIterations occurs

### ISSUE THREAD

**Issue by scsammyk** [ESPresense/ESPresense-companion#432]
The output coordinates of each of the three devices I am tracking is fairly accurate (to within a couple meters) but the chosen room is incorrect. Digging in a little deeper it looks like for some reason the localization algorithm is timing out or running through too many iterations and defaulting to a confidence of 1 for each floor which is then confusing the Best Scenario room and possibly causing an issue with plotting the tracked devices on the map. I have attached a screenshot from one of the tracked devices. In that screenshot the tracker is physically in the "Back Room" on the "First floor" and the coordinates properly reflect that but it is being reported as being in the "Basement"

Summary of issues being encountered:
  -Best Scenario room is always wrong (seems to be stuck on "Basement" for all devices)
  -Devices are not plotted on the map (on any floor)
  -The "Confidence" for a specific device being on all floors is 1
  -The "ReasonForExit" for all floors is "ExceedIterations"

Does the algorithm not do well with too many base stations? I currently have 12 active base stations

![Screenshot 2023-11-28 at 10 37 11 AM](https://github.com/ESPresense/ESPresense-companion/assets/20798551/009beb67-2294-4b8f-87d9-0be33d1e138a)

**Comment by DTTerastar** [comment]
ExceededIterations means we couldn't find a minimum on the error function.  It usually means something is wildly off.  It can also occur when our starting guess is so bad that moving in any direction caused MORE error.  I'll have to add some logging for this case.
