### ISSUE TITLE
Improve how the algorithm decides which intersection to choose

### ISSUE THREAD

**Issue by sanctas** [ESPresense/ESPresense-companion#473]
Hello. I use Espresense Companion for a few things, but one of them is tracking whether or not my trash bin is out. I track the trash collection days and I can set reminders and alerts to bug me to put the trash out. It's a cool and fun automation that I actually get a lot of functional use out of. My trash bin has a BLE Beacon attached to it. 

The problem is, the software has a lot of trouble figuring out where it is when it's out (it also has a lot of trouble with it in general, even when not out). I have brick walls which obviously cause a lot of issues trying to track something outside, however I can consistently have 5+ nodes connected to the trash bin even when it's out on the street. 

See the image below, with the red "X" I drew indicating the bin's actual location.

![image](https://github.com/ESPresense/ESPresense-companion/assets/136722448/044d152e-df16-46be-be27-c6714e7da2bd)

Looking at the data in the rings, I can see how making a determination on the distances of connected ESP32's alone will be difficult. Both intersections of the pink (Kitchen) and grey (Office) circles (which are the closest two circles) have pretty equal values. I'm not sure if it could also be biased by attempting to keep tracked objects inside the marked house. I haven't checked to see if that is apart of the algorithm. 

This problem perplexed me, the best solution would be to have a much better placed ESP32, but that isn't possible. It would have to be outside, where I don't have outlets (and I would need to waterproof it), or the south most point of the Garage, which also doesn't have outlets.

It perplexed me until I considered that simply having 5 connected node distances isn't the only data I have. I also have a *lack of data* from nodes that are unable to connect to the trash bin beacon. 

Looking back at the image I shared, the Trash Bin Beacon is nearly *on top* of the Living Room Node. This certainly cannot be true, because the Living Room node isn't able to detect the beacon at all!

So I propose a change to how the algorithm handles cases where confidence of the location is low. (In the image I provided, the confidence of the location is low -- around 25 max, mostly hovering at 22. 

If the confidence is very low, the software should also "push" the beacon away from nodes that, based on predicted location, should be connected but are not. Like my Living Room Node, in this example. 

I would like the developer's thoughts on this. Some other things I would like is the ability to specify that some beacons will *never* be X meters away from or close to a node. Like my Trash Bin will never be 5 meters or less away from the Living Room node, or 10 meters or less away from my Master Bedroom node. This could help in cases like Pets (with beacon collars) that aren't allowed in specific rooms, as well.

**Comment by DTTerastar** [comment]
Yes, I think this is a great idea.  I'm also working on something similar with variance calculation.  We need to be able to keep track of the interval that packets are expected in.  If reception becomes spotty it should be treated like it's a large distance measurement with a large variance.
