### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ScottG489** [ESPresense/ESPresense-companion#48]
I noticed a higher load average on my system and realized it was caused by this addon. I don't have any specific information about what might have been causing this, but I know this is in early development so I thought I'd report it so you're aware.

Otherwise, addon has been great and excited to see where things go with it :)

**Comment by DTTerastar** [comment]
It does some pretty cpu intensive things to discover the X/Y/Z location.  It is expected to use a decent amount of CPU.  How many items were you tracking?  How much cpu did you see used?

**Comment by ScottG489** [comment]
Will collect more data and let you know.

For a period of 2 hours the other day it looks like about 20% on average. I also recently removed tracking of all devices, so I'll see how much of an improvement there is.

For some specs, I'm running HAOS in vbox on a NUC Intel(R) Celeron(R) J4005 CPU @ 2.00GHz with 1 CPU allocated.

Also not sure if it's affecting this addon, but I think I need to reconfigure ESPresense to not report all devices because my mosquitto usage has gone from under 1% to like 7%.
