### ISSUE TITLE
Feature Request: Side view or 3D-Model

### ISSUE THREAD

**Issue by supaeasy** [ESPresense/ESPresense-companion#520]
Since boundaries are not only set in x and y but in z as well it should be rather easy to show a multi-story home from the side. This would improve usability and overview.

Please add a visualisation from the side (from x or y axis) In addition to the top-down view (from the z-axis). 
Best case: A semi-transparent rotatable 3D-Object showing all floors

**Comment by hdurdle** [comment]
Something like this?

![image](https://github.com/ESPresense/ESPresense-companion/assets/4083861/0da67cbf-2ee7-4d84-b3df-8985bd813a99)

A work in progress, it consumes the position info direct from the mqtt server and puts spheres for each tracked object in a wireframe built from the boundary heights and rooms defined in the config.

**Comment by supaeasy** [comment]
Yes! Exactly what i meant. Awesome!

**Comment by hdurdle** [comment]
Code to run it here:  https://github.com/hdurdle/espc3d

The code should be generic enough to work for any layout that follows the rules for espresense-companion's config, but I've not tried it on anything other than my house!  I'd love to see what it looks like for others.
