### ISSUE TITLE
no devices on map 2024.4

### ISSUE THREAD

**Issue by arne182** [ESPresense/ESPresense-companion#620]
The devices list is not filling up. There are only a few devices listed but if you check the web interface the devices are found. Any idea what could be the issue?

**Comment by azdlowry** [comment]
I think I'm seeing the same behaviour. Not sure when exactly it started but it's in the last few weeks. I'll do some investigation when I get a chance.

**Comment by azdlowry** [comment]
> I think I'm seeing the same behaviour. Not sure when exactly it started but it's in the last few weeks. I'll do some investigation when I get a chance.

Little more info - the companion was running as I was getting device location updates, it was just the dashboard that wasn't working. Restarting the companion add-in seems to have fixed it though.
