### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by mcinnes01** [ESPresense/ESPresense-companion#65]
Hi I appreciate it's still WIP but wondered if there is any documentation or a setup guide/video?

Many thanks

Andy

**Comment by DTTerastar** [comment]
I've been thinking about doing a video... Do you have specific questions?

**Comment by iamandymcinnes** [comment]
Probably for a basic starter a full walk through, what is it, what does does it do/not do, how do you use it / connect it with your espresence config in HA. Also probably worth detailing any gotchas, ways of tuning the accuracy, building a data model assuming it helps you do that. Also some basic examples of using it in an automation, maybe working with motion sensors/light as this is fairly typical use case.

Then if you wanted to do a more advance video, any optional or advanced configuration opportunities. Advanced usages maybe combining it with a bayesian sensor to improve accuracy for room pressence. Real life implementation examples combining the above and motion and how it's used in an automation. Address any questions like number of people in a room, realtime tracking, handling guests in the house.

**Comment by DTTerastar** [comment]
Well it doesn't work yet, so I don't really have any advice yet.  I need others to help figure all that out!

**Comment by Ar2rZ** [comment]
will be good to have at least simple setup guide in HA.

**Comment by DTTerastar** [comment]
I think the readme has that, no?
@Ar2rZ

**Comment by AlmostInteractive** [comment]
> Well it doesn't work yet, so I don't really have any advice yet. I need others to help figure all that out!

Which parts of this project don't yet work?  I installed it yesterday, setup the map, the nodes, and the devices to track.  It's triangulating my phone's position from four nodes, but it's consistently off by at least 3 meters and it doesn't actually show up on the map (the nodes do, but the phone doesn't).  Is that something I did wrong, or something that isn't working yet in the app?

**Comment by DTTerastar** [comment]
The exact locations are not perfect, but for me the z is way weird.  Stuff switches between floors when it shouldn't.  Your position is off the map?  That may be because of a bad rssi@1m.  I need to make the devices clickable in the list view so you can fix that.

**Comment by joshuaboniface** [comment]
I've found the same with z being weird and jumping a lot, but otherwise it's relatively decent.

Personally I'd love to see more detail about what the knobs in the config file do. For instance I see `sigma` is 0.3 by default in the code but 0.1 in the example conf, but it's not clear what this does.

**Comment by DTTerastar** [comment]
That value is the amount of weighting to add to the nearer nodes vs the far ones.  I use a gaussian distribution (bell curve).

**Comment by joshuaboniface** [comment]
Solid! The other thing I'm really not clear on is when you'd want to put a node into multiple floors. I suppose this has the effect of making the node "count" for multiple floors, but should that be done? Or what situations might that be ideal vs. not?

**Comment by DTTerastar** [comment]
That's a good question and one I honestly don't know the answer to.  I already rank the nodes by distance and throw out measures that won't help so it might not matter.  

This whole thing is an experiment.  If someone could try both scenarios and see which works better that was be awesome!

**Comment by joshuaboniface** [comment]
I did give it a bit of a shot, I saw it in your example so figured there might be a good case for it somewhere. ;-) But I found it didn't really "help" anything and did cause some wonkiness, at least with my house/node layout, so I removed them.

**Comment by jlvandusen** [comment]
I waned to chime in here - I have a basic espresence setup with over 10 room nodes
I found your companion and I am trying to now build out my dimensions.. I have the basic coordinates now plotted for lets say the 1st floor...

i start from 0,0 and make my way around each room and such... I have the enter 1st floor mapped now with coordinates for each corner of the rooms.. There are 7 rooms just on 1st floor.... so far
now... to convert this to your yaml for the rooms...

I have my garage coordinates as follows... Start 0,0 then up 6,0 then right to 6,6 and then back to 0,6
How does this look in your yaml then...
I see for yours there are lots of coordinates
      - name: Garage
        points:
          - [0, 18]
          - [1.5, 18]
          - [1.5, 19.2]
          - [4, 19.2]
          - [4, 9]
          - [0, 9]
          - [0, 18]
   
I was thinking mine would only be
      - name: Garage
        points:
          - [0, 0]
          - [6, 0]
          - [6, 6
          - [0, 6]

am I over complicating this?

**Comment by DTTerastar** [comment]
My house has lots of stupid angles.  If you have a square room only 4 points are needed.

**Comment by jlvandusen** [comment]
I ended up manually determining the points.. there is a start and you have to go back to the start so there should be 
start point
right most lower corner
upper right corner
back over to the upper left corner
back to start point

So 5 points total...

**Comment by johntdyer** [comment]
A Video would be a great consolation if you dont have the time to write docs, appreciate anything you can offer :)

**Comment by m0vva** [comment]
Some additional items I'd appreciate to see in the documentation.

I'm confused in the config.yaml as to when/why you would add a node to many floors?  

In the UI, what the "Show All" is meant to do - in mine it doesn't shows all devices and doesn't show all floors, it changes nothing in the UI as far as I can tell.

**Comment by DTTerastar** [comment]
Being able to pick which nodes participate in each floor seemed like a good idea at the time :)  No particular reason just a knob to try and tweak.

Show all was broken #388 fixes it.

**Comment by supaeasy** [comment]
Show All doesn't do anything for me in 0.6.2 - broken again?

**Comment by DTTerastar** [comment]
It's working for me atm

**Comment by supaeasy** [comment]
Sorry yes it works after I added all Sensors to all floors. Which I didn't feel should be necessary but yeah.. 
It works kind of fine so far, xy wise. Z is another story. I have 7 floors (Terrassed house with mezzanine floors) covered in 12 Sensors and the floor is really never right for my devices. Don't know how to fix this, made a suggestion to add Wall/floor absorption.

**Comment by jlvandusen** [comment]
@DTTerastar - is there a way to get the correct scale in your web tool? I cannot zoom out enough and then read the variables to do the scale of my home and rooms correctly... 

@DTTerastar - In Espresence (HA addon) I don't see any of my beacons or sensors floating around - MQTT definately sees them and is reporting them in the correct rooms but the ESPresence add-on for Home Assistance doesnt visually see them to troubleshoot.

**Comment by supaeasy** [comment]
You probably have a multi floor home and/or not enough sensors on the same level for triangulation. Try assigning multiple floors per sensor e.g. 
'''
floor: ["first", "second"]
'''
Ideally, there should be a sensor in each corner  plus as many more in between as you like.

**Comment by giovacode** [comment]
First of all thank you so much for this great project !
I'm also missing of some documentation. I see a lot of settings with no clue about their role.

Regarding companion , for example i cannot see my tile on the map ; it is present in device page, it has 2 fixes, but scale = n/a
i suspect that scale , but how/where to set this? why it exists ?
optimisation section is also really obscure to me :)
