### ISSUE TITLE
Settings 404s

### ISSUE THREAD

**Issue by briancmoses** [ESPresense/ESPresense-companion#8]
I added the repository, added the ESPresense Companion, added the companion to my Sidebar and opened it up.  I had a few problems.  I totally understand this is an early release,  I just wanted to share what I found.

Firstly the Settings link 404s.  It seems to be pointing at a  `http://<insert Home Assistant name/IP here>:8123/settings`   

```
<a href="/settings" class="svelte-r1ko2w">Settings</a>
```

Secondly, the link  in the add-on's info page for, "Visit the [ESPresense Companion](https://espresense.com/) page for more details."  just goes to the root of ESPresense.com.  I poked around the ESPresense.github.io repository, but couldn't find the new page, yet. 

The diagram seems to show a number of rooms and base stations which don't align with the name's of my rooms and/or base stations.

![2022-11-29_13-25-04](https://user-images.githubusercontent.com/5208571/204629140-69806d16-69a4-4fbf-88f5-ccd2cffd6f3d.jpg)

I tried removing the add-on, its repository and re-installing a couple times.  It didn't seem to change anything for me.

**Comment by DTTerastar** [comment]
Those are all expected at this point.  You need to edit the /config/espresense/config.yaml to match your house.  Settings is not started yet.  And documentation is not written yet on espresense.com...
Rome wasn't built in a day :)

**Comment by briancmoses** [comment]
Thanks for the response!  I figured I'd submit an issue just in case something might've been out of whack.  

I'll take a look at the config,  thanks for pointing me in the right direction!

**Comment by DTTerastar** [comment]
Settings doesn't get a 404 anymore. (It's still just a dummy page tho)
